dist: bionic
language: cpp

services:
  - docker

install:
  - docker build -t oesse/find-critical-path .

script:
  - docker run -v $PWD:$PWD -w $PWD oesse/find-critical-path /bin/sh -c "cmake -H. -Bbuild && cmake --build build/ && cmake --build build/ --target test"
